import type { SoundId } from '@/content/copy';

// Generated by scripts/generate-sounds.mjs.
export const SOUND_FILES: Record<Exclude<SoundId, 'none'>, number> = {
  rain: require('@/assets/sounds/rain.wav'),
  brown: require('@/assets/sounds/brown.wav'),
  drone: require('@/assets/sounds/drone.wav'),
};
