import { Image, StyleSheet, View, useWindowDimensions } from 'react-native';

import { useTheme } from '@/theme/theme';

// Generated by scripts/generate-paper.mjs.
const INK = require('@/assets/textures/paper-ink.png');
const CHALK = require('@/assets/textures/paper-chalk.png');
const TILE = 384;

// A tiled washi grain. Dark specks on light paper, light specks on dark paper.
// Tiles are laid out explicitly because `resizeMode="repeat"` does not repeat on web.
export function PaperTexture({ tone, opacity }: { tone?: 'ink' | 'chalk'; opacity?: number }) {
  const { scheme } = useTheme();
  const { width, height } = useWindowDimensions();
  const grain = tone ?? (scheme === 'dark' ? 'chalk' : 'ink');
  const cols = Math.ceil(width / TILE);
  const rows = Math.ceil(height / TILE);
  // Pale fibres read much stronger on dark paper, so chalk is quieter by default.
  const strength = opacity ?? (grain === 'chalk' ? 0.4 : 1);

  return (
    <View pointerEvents="none" style={[StyleSheet.absoluteFill, styles.clip, { opacity: strength }]}>
      {Array.from({ length: rows * cols }, (_, i) => (
        <Image
          key={i}
          source={grain === 'ink' ? INK : CHALK}
          style={{
            position: 'absolute',
            width: TILE,
            height: TILE,
            left: (i % cols) * TILE,
            top: Math.floor(i / cols) * TILE,
          }}
        />
      ))}
    </View>
  );
}

const styles = StyleSheet.create({
  clip: { overflow: 'hidden' },
});
